AllCops:
  DisabledByDefault: true
  UseCache: false

Style/RedundantInterpolation:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UriRegexp:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/RescueType:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/RedundantWithObject:
  Enabled: true

Lint/BigDecimalNew:
  Enabled: true

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true

Lint/SafeNavigationWithEmpty:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Style/Sample:
  Enabled: true

Style/RedundantSort:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
